## 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml   # 注意：MP中指定xml路径通常用 mapper-locations
  type-aliases-package: com.hao.usercenter.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 下划线转驼峰
  global-config:
    db-config:
      # 逻辑删除
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
